package com.webianks.exp.scout.model;

import java.util.List;

/**
 * Created by R Ankit on 20-02-2017.
 */

public class TypedRelations {


    /**
     * status : OK
     * usage : By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html
     * totalTransactions : 2
     * language : english
     * model : 2453ad8b-defe-46b7-b464-7a69fc736d17
     * typedRelations : [{"arguments":[{"entities":[{"id":"-E1","text":"from","type":"FROM"}],"part":"first","text":"from"},{"entities":[{"id":"-E2","text":"Ravi","type":"USERNAME"}],"part":"second","text":"Ravi"}],"score":"0.949951","sentence":"PDFs from Ravi in the last 3 days","type":"sentFrom"}]
     */

    private String status;
    private String usage;
    private String totalTransactions;
    private String language;
    private String model;
    private List<TypedRelationsBean> typedRelations;

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getUsage() {
        return usage;
    }

    public void setUsage(String usage) {
        this.usage = usage;
    }

    public String getTotalTransactions() {
        return totalTransactions;
    }

    public void setTotalTransactions(String totalTransactions) {
        this.totalTransactions = totalTransactions;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public List<TypedRelationsBean> getTypedRelations() {
        return typedRelations;
    }

    public void setTypedRelations(List<TypedRelationsBean> typedRelations) {
        this.typedRelations = typedRelations;
    }

    public static class TypedRelationsBean {
        /**
         * arguments : [{"entities":[{"id":"-E1","text":"from","type":"FROM"}],"part":"first","text":"from"},{"entities":[{"id":"-E2","text":"Ravi","type":"USERNAME"}],"part":"second","text":"Ravi"}]
         * score : 0.949951
         * sentence : PDFs from Ravi in the last 3 days
         * type : sentFrom
         */

        private String score;
        private String sentence;
        private String type;
        private List<ArgumentsBean> arguments;

        public String getScore() {
            return score;
        }

        public void setScore(String score) {
            this.score = score;
        }

        public String getSentence() {
            return sentence;
        }

        public void setSentence(String sentence) {
            this.sentence = sentence;
        }

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public List<ArgumentsBean> getArguments() {
            return arguments;
        }

        public void setArguments(List<ArgumentsBean> arguments) {
            this.arguments = arguments;
        }

        public static class ArgumentsBean {
            /**
             * entities : [{"id":"-E1","text":"from","type":"FROM"}]
             * part : first
             * text : from
             */

            private String part;
            private String text;
            private List<EntitiesBean> entities;

            public String getPart() {
                return part;
            }

            public void setPart(String part) {
                this.part = part;
            }

            public String getText() {
                return text;
            }

            public void setText(String text) {
                this.text = text;
            }

            public List<EntitiesBean> getEntities() {
                return entities;
            }

            public void setEntities(List<EntitiesBean> entities) {
                this.entities = entities;
            }

            public static class EntitiesBean {
                /**
                 * id : -E1
                 * text : from
                 * type : FROM
                 */

                private String id;
                private String text;
                private String type;

                public String getId() {
                    return id;
                }

                public void setId(String id) {
                    this.id = id;
                }

                public String getText() {
                    return text;
                }

                public void setText(String text) {
                    this.text = text;
                }

                public String getType() {
                    return type;
                }

                public void setType(String type) {
                    this.type = type;
                }
            }
        }
    }
}
